[build]
builder = "NIXPACKS"

[phases.setup]
aptPkgs = ["tesseract-ocr", "tesseract-ocr-tur"]

[phases.build]
cmds = [
    "pip install -r requirements.txt",
    "playwright install chromium",
    "playwright install-deps chromium"
]

[start]
cmd = "python -u main.py"
